### ISSUE TITLE
WHAMP inputs

### ISSUE THREAD

**Issue by AlexDs20** [irfu/irfu-matlab#45]
This is a suggestion of improvement related to WHAMP.

The whamp.plot_f takes the input temperature in keV while whamp.run takes the temperature in eV.
The two functions takes the same structure format for each species.

I suggest to change the unit temperature input of whamp.plot_f to eV so that the same structure can be used for whamp.run and whamp.plot_f.

This implies the following changes in plot_f.m file (I think this is an exhaustive list):
line13:
%     t  - temperature [keV]                                                                => %     t  - temperature [eV]
line 183:
  vt(j)=sqrt(2*e * 1000*t(j)/mm(j)); % [m/s] (t in keV therefore *1000)     => vt(j)=sqrt(2*e *(j)/mm(j));
line 267:
	title(h,['1st comp: T=' num2str(t(1),3) 'keV'...                               => 	title(h,['1st comp: T=' num2str(t(1),3) 'eV'...

I think that's it.

Best,
Alexandre

**Comment by thomas-nilsson-irfu** [comment]
Dear @AlexDs20,
thank you for your suggestion.

I can see your point about having the temperature units more self-consistent inside the WHAMP package (_eV_ & _eV_ instead of _eV_ & _keV_), however this package is mostly taken from our other repository found here: [irfu/whamp](https://github.com/irfu/whamp). As @vaivads was one of the last contributors there I would refer this issue to him to decide.

We would perhaps not like the two codes to diverge to much (especially when it comes to what arguments each function takes).
