### ISSUE TITLE
SPICE kernel directory

### ISSUE THREAD

**Issue by vaivads** [irfu/irfu-matlab#6]
There should be possibility to define SPICE directory variable that is kept across the sessions (similar to CAA credentials). Also, there should some good solution for metakernel files that work independently of computer (local or spis).

**Comment by thomas-nilsson-irfu** [comment]
This issue has come up to life again..

Now we have some code (in `devel`) which makes SolO metakernels loadable independently of computer used (local or Spis/Brain)*, at wherever path it is mounted on the computer (as long as it is not too long path for SPICE to load).

Following discussion with @Niked82 (on Slack, 2020-11-06T13:25) the question came up: Is there some way of similarly loading SPICE metakernels for `BepiColombo`, `ParkerSolarProbe`**, etc.? (these are locally currently synced to `/share/SPICE/` on IRFU's servers). Presently there is no code for adapting metakernels from these missions to local mounting paths, but it should be possible to do similar to the SolO code.

Problems to solve include each mission having slightly different naming standard for "flown" vs "predicted" metakernels, (`JUICE` have several different alternate planned orbits). It should perhaps use an argument to ask for rootPath (as we can not use dbRootPath for mission we do not yet have a lookup database code for)..


And of course there are a few asterisks: 
*As long as it is not Windows (due to `CRLF` and `\` instead of `/` as file separator), and as long as a local git clone of the official SolO spice repository is found as in a subfolder SPICE in the folder used to initialize one instance of the solo.db_init(). (Note: locally at IRFU it is found in /data/solo/SPICE/).
** ParkerSolarProbe is synced in a new script, kernels not yet fully tested locally at IRFU. Also it does not appear to have a mission common metakernel so presently it is a test kernel created by my script..

**Comment by thomas-nilsson-irfu** [comment]
I believe this issue is now solved (in devel-branch) using `load_mkernel('mission', 'predicted_or_flown')`.
The script will ask for local path to SPICE repository (in case of SolO on IRFU's servers that is: `/data/solo/SPICE/`), and this path will be stored between Matlab sessions using `datastore('spice_paths', 'mission')`. If these paths are not found during next session it will ask again, but it will only load one metakernel per session and per mission (& per flown/predicted status).

I am therefor closing this old issue, finally! :)
