### ISSUE TITLE
onera

### ISSUE THREAD

**Issue by vaivads** [irfu/irfu-matlab#7]
onera requires knowledge of compilator, see example below. This needs to be fixed so that there is no compilator needed (static libraries instead of dynamic?). 

Output of running Mac

> > t=irf_time(now,'datenum2epoch')+[1:10]; t=t(:);
> > frGSE = [t rand(numel(t),1)-0.5 rand(numel(t),1)-0.5 rand(numel(t),1)-0.5];
> > timeDatenum=irf_time(frGSE(:,1),'epoch2datenum');
> > frGEO = onera_desp_lib_coord_trans(frGSE(:,2:4),'gse2geo',timeDatenum);
> > ??? Error using ==> loadlibrary at 441
> > Failed to preprocess the input file.
> >  Output from preprocessor is:/bin/bash: gcc-4.2: command not found

Error in ==> onera_desp_lib_load at 39
    loadlibrary(libfile,headerfile,'alias','onera_desp_lib');

Error in ==> onera_desp_lib_coord_trans at 38
onera_desp_lib_load;

**Comment by thomas-nilsson-irfu** [comment]
Dear @vaivads, sorry to bother you with this old issue. However as it is still listed as "open" I have to ask if this is still a present day issue or has this become somewhat of a "zombie issue" here on Github irfu-matlab?

Since this issue was first created in irfu-matlab we have imported at least one new version of onera_desp_lib_maci64.dylib, see commit 422cec74f448829c7d6c5f7219d3654df10cbff8.

**Comment by thomas-nilsson-irfu** [comment]
Closing this issue, if it is still active please feel free to re-open.
